// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: bsuser.proto

package bsuser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BsuserClient is the client API for Bsuser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BsuserClient interface {
	// group: base
	InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
}

type bsuserClient struct {
	cc grpc.ClientConnInterface
}

func NewBsuserClient(cc grpc.ClientConnInterface) BsuserClient {
	return &bsuserClient{cc}
}

func (c *bsuserClient) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, "/bsuser.Bsuser/initDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BsuserServer is the server API for Bsuser service.
// All implementations must embed UnimplementedBsuserServer
// for forward compatibility
type BsuserServer interface {
	// group: base
	InitDatabase(context.Context, *Empty) (*BaseResp, error)
	mustEmbedUnimplementedBsuserServer()
}

// UnimplementedBsuserServer must be embedded to have forward compatible implementations.
type UnimplementedBsuserServer struct {
}

func (UnimplementedBsuserServer) InitDatabase(context.Context, *Empty) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDatabase not implemented")
}
func (UnimplementedBsuserServer) mustEmbedUnimplementedBsuserServer() {}

// UnsafeBsuserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BsuserServer will
// result in compilation errors.
type UnsafeBsuserServer interface {
	mustEmbedUnimplementedBsuserServer()
}

func RegisterBsuserServer(s grpc.ServiceRegistrar, srv BsuserServer) {
	s.RegisterService(&Bsuser_ServiceDesc, srv)
}

func _Bsuser_InitDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BsuserServer).InitDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bsuser.Bsuser/initDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BsuserServer).InitDatabase(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Bsuser_ServiceDesc is the grpc.ServiceDesc for Bsuser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bsuser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bsuser.Bsuser",
	HandlerType: (*BsuserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initDatabase",
			Handler:    _Bsuser_InitDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bsuser.proto",
}
