// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/kebin6/bsuser-rpc/ent/bsuser"
)

const errInvalidPage = "INVALID_PAGE"

const (
	listField     = "list"
	pageNumField  = "pageNum"
	pageSizeField = "pageSize"
)

type PageDetails struct {
	Page  uint64 `json:"page"`
	Size  uint64 `json:"size"`
	Total uint64 `json:"total"`
}

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

const errInvalidPagination = "INVALID_PAGINATION"

type BsuserPager struct {
	Order  bsuser.OrderOption
	Filter func(*BsuserQuery) (*BsuserQuery, error)
}

// BsuserPaginateOption enables pagination customization.
type BsuserPaginateOption func(*BsuserPager)

// DefaultBsuserOrder is the default ordering of Bsuser.
var DefaultBsuserOrder = Desc(bsuser.FieldID)

func newBsuserPager(opts []BsuserPaginateOption) (*BsuserPager, error) {
	pager := &BsuserPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultBsuserOrder
	}
	return pager, nil
}

func (p *BsuserPager) ApplyFilter(query *BsuserQuery) (*BsuserQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// BsuserPageList is Bsuser PageList result.
type BsuserPageList struct {
	List        []*Bsuser    `json:"list"`
	PageDetails *PageDetails `json:"pageDetails"`
}

func (b *BsuserQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...BsuserPaginateOption,
) (*BsuserPageList, error) {

	pager, err := newBsuserPager(opts)
	if err != nil {
		return nil, err
	}

	if b, err = pager.ApplyFilter(b); err != nil {
		return nil, err
	}

	ret := &BsuserPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	count, err := b.Clone().Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		b = b.Order(pager.Order)
	} else {
		b = b.Order(DefaultBsuserOrder)
	}

	b = b.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := b.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}
