// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/kebin6/bsuser-rpc/ent/bsuser"
	"github.com/kebin6/bsuser-rpc/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bsuserMixin := schema.Bsuser{}.Mixin()
	bsuserMixinFields0 := bsuserMixin[0].Fields()
	_ = bsuserMixinFields0
	bsuserMixinFields1 := bsuserMixin[1].Fields()
	_ = bsuserMixinFields1
	bsuserFields := schema.Bsuser{}.Fields()
	_ = bsuserFields
	// bsuserDescCreatedAt is the schema descriptor for created_at field.
	bsuserDescCreatedAt := bsuserMixinFields0[1].Descriptor()
	// bsuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	bsuser.DefaultCreatedAt = bsuserDescCreatedAt.Default.(func() time.Time)
	// bsuserDescUpdatedAt is the schema descriptor for updated_at field.
	bsuserDescUpdatedAt := bsuserMixinFields0[2].Descriptor()
	// bsuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bsuser.DefaultUpdatedAt = bsuserDescUpdatedAt.Default.(func() time.Time)
	// bsuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bsuser.UpdateDefaultUpdatedAt = bsuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bsuserDescStatus is the schema descriptor for status field.
	bsuserDescStatus := bsuserMixinFields1[0].Descriptor()
	// bsuser.DefaultStatus holds the default value on creation for the status field.
	bsuser.DefaultStatus = bsuserDescStatus.Default.(uint8)
}
