// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilUpdatedAt(value *time.Time) *BsuserUpdate {
	if value != nil {
		return b.SetUpdatedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilUpdatedAt(value *time.Time) *BsuserUpdateOne {
	if value != nil {
		return b.SetUpdatedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilUpdatedAt(value *time.Time) *BsuserCreate {
	if value != nil {
		return b.SetUpdatedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilStatus(value *uint8) *BsuserUpdate {
	if value != nil {
		return b.SetStatus(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilStatus(value *uint8) *BsuserUpdateOne {
	if value != nil {
		return b.SetStatus(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilStatus(value *uint8) *BsuserCreate {
	if value != nil {
		return b.SetStatus(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilName(value *string) *BsuserUpdate {
	if value != nil {
		return b.SetName(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilName(value *string) *BsuserUpdateOne {
	if value != nil {
		return b.SetName(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilName(value *string) *BsuserCreate {
	if value != nil {
		return b.SetName(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilMobile(value *string) *BsuserUpdate {
	if value != nil {
		return b.SetMobile(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilMobile(value *string) *BsuserUpdateOne {
	if value != nil {
		return b.SetMobile(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilMobile(value *string) *BsuserCreate {
	if value != nil {
		return b.SetMobile(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilPwd(value *string) *BsuserUpdate {
	if value != nil {
		return b.SetPwd(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilPwd(value *string) *BsuserUpdateOne {
	if value != nil {
		return b.SetPwd(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilPwd(value *string) *BsuserCreate {
	if value != nil {
		return b.SetPwd(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilTotalAmount(value *string) *BsuserUpdate {
	if value != nil {
		return b.SetTotalAmount(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilTotalAmount(value *string) *BsuserUpdateOne {
	if value != nil {
		return b.SetTotalAmount(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilTotalAmount(value *string) *BsuserCreate {
	if value != nil {
		return b.SetTotalAmount(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilValidAmount(value *string) *BsuserUpdate {
	if value != nil {
		return b.SetValidAmount(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilValidAmount(value *string) *BsuserUpdateOne {
	if value != nil {
		return b.SetValidAmount(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilValidAmount(value *string) *BsuserCreate {
	if value != nil {
		return b.SetValidAmount(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilInviteCode(value *string) *BsuserUpdate {
	if value != nil {
		return b.SetInviteCode(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilInviteCode(value *string) *BsuserUpdateOne {
	if value != nil {
		return b.SetInviteCode(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilInviteCode(value *string) *BsuserCreate {
	if value != nil {
		return b.SetInviteCode(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdate) SetNotNilInvitedBy(value *uint64) *BsuserUpdate {
	if value != nil {
		return b.SetInvitedBy(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserUpdateOne) SetNotNilInvitedBy(value *uint64) *BsuserUpdateOne {
	if value != nil {
		return b.SetInvitedBy(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BsuserCreate) SetNotNilInvitedBy(value *uint64) *BsuserCreate {
	if value != nil {
		return b.SetInvitedBy(*value)
	}
	return b
}
